-- =========================
-- 1. TẠO DATABASE
-- =========================
DROP DATABASE IF EXISTS ComputerSpace;
CREATE DATABASE ComputerSpace
CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci;

USE ComputerSpace;

SET FOREIGN_KEY_CHECKS = 0;

-- =========================
-- 2. BẢNG TÀI KHOẢN
-- =========================
CREATE TABLE TAI_KHOAN (
    MaTK INT AUTO_INCREMENT PRIMARY KEY,
    TenDangNhap VARCHAR(50) NOT NULL UNIQUE,
    MatKhau VARCHAR(255) NOT NULL,
    VaiTro ENUM('KHACH_HANG', 'QUAN_TRI_VIEN') NOT NULL,
    TrangThai TINYINT NOT NULL DEFAULT 1,
    NgayTao DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    NgayDangNhapCuoi DATETIME NULL
) ENGINE=InnoDB;

CREATE TABLE KHACH_HANG (
    MaKH INT AUTO_INCREMENT PRIMARY KEY,
    MaTK INT NOT NULL UNIQUE,
    HoTen VARCHAR(100) NOT NULL,
    SDT VARCHAR(15) UNIQUE,
    Email VARCHAR(100) UNIQUE,
    DiaChi VARCHAR(255),
    CONSTRAINT FK_KHACH_HANG_TAI_KHOAN
        FOREIGN KEY (MaTK) REFERENCES TAI_KHOAN(MaTK)
        ON DELETE CASCADE
        ON UPDATE CASCADE
) ENGINE=InnoDB;

CREATE TABLE QUAN_TRI_VIEN (
    MaNV INT AUTO_INCREMENT PRIMARY KEY,
    MaTK INT NOT NULL UNIQUE,
    HoTen VARCHAR(100) NOT NULL,
    SDT VARCHAR(15) UNIQUE,
    Email VARCHAR(100) UNIQUE,
    ChucVu VARCHAR(100),
    CONSTRAINT FK_QUAN_TRI_VIEN_TAI_KHOAN
        FOREIGN KEY (MaTK) REFERENCES TAI_KHOAN(MaTK)
        ON DELETE CASCADE
        ON UPDATE CASCADE
) ENGINE=InnoDB;

-- =========================
-- 3. BẢNG SẢN PHẨM
-- =========================
CREATE TABLE LOAI_SAN_PHAM (
    MaLoaiSP INT AUTO_INCREMENT PRIMARY KEY,
    TenLoaiSP VARCHAR(100) NOT NULL UNIQUE,
    MoTa TEXT
) ENGINE=InnoDB;

CREATE TABLE SAN_PHAM (
    MaSP INT AUTO_INCREMENT PRIMARY KEY,
    TenSP VARCHAR(255) NOT NULL,
    MaLoaiSP INT NOT NULL,
    ThuongHieu VARCHAR(100),
    GiaBan DECIMAL(15,2) NOT NULL DEFAULT 0,
    SoLuongTon INT NOT NULL DEFAULT 0,
    BaoHanhThang INT NOT NULL DEFAULT 0,
    MoTaNgan TEXT,
    MoTaChiTiet LONGTEXT,
    TrangThai TINYINT NOT NULL DEFAULT 1,
    NgayTao DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    NgayCapNhat DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT FK_SAN_PHAM_LOAI
        FOREIGN KEY (MaLoaiSP) REFERENCES LOAI_SAN_PHAM(MaLoaiSP)
        ON DELETE RESTRICT
        ON UPDATE CASCADE
) ENGINE=InnoDB;

CREATE INDEX IDX_SAN_PHAM_MaLoaiSP ON SAN_PHAM(MaLoaiSP);
CREATE FULLTEXT INDEX IDX_SAN_PHAM_TenSP ON SAN_PHAM(TenSP);
CREATE INDEX IDX_SAN_PHAM_ThuongHieu ON SAN_PHAM(ThuongHieu);

CREATE TABLE ANH_SAN_PHAM (
    MaAnh INT AUTO_INCREMENT PRIMARY KEY,
    MaSP INT NOT NULL,
    DuongDanAnh VARCHAR(255) NOT NULL,
    LaAnhDaiDien TINYINT NOT NULL DEFAULT 0,
    CONSTRAINT FK_ANH_SAN_PHAM_SAN_PHAM
        FOREIGN KEY (MaSP) REFERENCES SAN_PHAM(MaSP)
        ON DELETE CASCADE
        ON UPDATE CASCADE
) ENGINE=InnoDB;

CREATE INDEX IDX_ANH_SAN_PHAM_MaSP ON ANH_SAN_PHAM(MaSP);

-- =========================
-- 4. BẢNG CHI TIẾT LINH KIỆN
-- =========================

CREATE TABLE CHI_TIET_MAIN (
    MaSP INT PRIMARY KEY,
    Chipset VARCHAR(100),
    Socket VARCHAR(50),
    KichThuocMain VARCHAR(50),
    HoTroCPU VARCHAR(255),
    SoKheRam INT,
    LoaiRam VARCHAR(50),
    DungLuongRamToiDa VARCHAR(50),
    KhePCIe VARCHAR(100),
    SoCongSATA INT,
    SoKheM2 INT,
    CongXuatHinh VARCHAR(255),
    CONSTRAINT FK_CHI_TIET_MAIN_SAN_PHAM
        FOREIGN KEY (MaSP) REFERENCES SAN_PHAM(MaSP)
        ON DELETE CASCADE
        ON UPDATE CASCADE
) ENGINE=InnoDB;

CREATE TABLE CHI_TIET_CPU (
    MaSP INT PRIMARY KEY,
    HangCPU VARCHAR(100),
    DongCPU VARCHAR(100),
    Socket VARCHAR(50),
    SoNhan INT,
    SoLuongLuong INT,
    XungNhipCoBan VARCHAR(50),
    XungNhipTurbo VARCHAR(50),
    CacheL1 VARCHAR(50),
    CacheL2 VARCHAR(50),
    TDP VARCHAR(50),
    CoGPU TINYINT DEFAULT 0,
    CONSTRAINT FK_CHI_TIET_CPU_SAN_PHAM
        FOREIGN KEY (MaSP) REFERENCES SAN_PHAM(MaSP)
        ON DELETE CASCADE
        ON UPDATE CASCADE
) ENGINE=InnoDB;

CREATE TABLE CHI_TIET_VGA (
    MaSP INT PRIMARY KEY,
    HangGPU VARCHAR(100),
    DungLuongVRAM VARCHAR(50),
    KieuBoNho VARCHAR(50),
    BusBoNho VARCHAR(50),
    XungNhip VARCHAR(50),
    TDP VARCHAR(50),
    CongKetNoi VARCHAR(255),
    SoQuat INT,
    KichThuocCard VARCHAR(100),
    DauCapNguon VARCHAR(100),
    CONSTRAINT FK_CHI_TIET_VGA_SAN_PHAM
        FOREIGN KEY (MaSP) REFERENCES SAN_PHAM(MaSP)
        ON DELETE CASCADE
        ON UPDATE CASCADE
) ENGINE=InnoDB;

CREATE TABLE CHI_TIET_CASE (
    MaSP INT PRIMARY KEY,
    HoTroMain VARCHAR(100),
    MauSac VARCHAR(50),
    ChatLieu VARCHAR(100),
    KichThuoc VARCHAR(100),
    HoTroNguon VARCHAR(100),
    SoLuongQuatHoTro INT,
    CoKinhCuongLuc TINYINT DEFAULT 0,
    CongTruocCase VARCHAR(255),
    CONSTRAINT FK_CHI_TIET_CASE_SAN_PHAM
        FOREIGN KEY (MaSP) REFERENCES SAN_PHAM(MaSP)
        ON DELETE CASCADE
        ON UPDATE CASCADE
) ENGINE=InnoDB;

CREATE TABLE CHI_TIET_NGUON (
    MaSP INT PRIMARY KEY,
    CongSuat VARCHAR(50),
    Chuan80Plus VARCHAR(50),
    CongKetNoi VARCHAR(255),
    KichThuocNguon VARCHAR(100),
    DienApVao VARCHAR(100),
    DauCapNguon VARCHAR(255),
    CONSTRAINT FK_CHI_TIET_NGUON_SAN_PHAM
        FOREIGN KEY (MaSP) REFERENCES SAN_PHAM(MaSP)
        ON DELETE CASCADE
        ON UPDATE CASCADE
) ENGINE=InnoDB;

CREATE TABLE CHI_TIET_TAN_NHIET (
    MaSP INT PRIMARY KEY,
    LoaiTanNhiet VARCHAR(100),
    TuongThichCPU VARCHAR(255),
    KichThuocRadiator VARCHAR(100),
    SoQuat INT,
    TocDoQuat VARCHAR(50),
    DoOn VARCHAR(50),
    LED VARCHAR(50),
    KichThuocTan VARCHAR(100),
    CONSTRAINT FK_CHI_TIET_TAN_NHIET_SAN_PHAM
        FOREIGN KEY (MaSP) REFERENCES SAN_PHAM(MaSP)
        ON DELETE CASCADE
        ON UPDATE CASCADE
) ENGINE=InnoDB;

CREATE TABLE CHI_TIET_O_CUNG (
    MaSP INT PRIMARY KEY,
    LoaiOCung VARCHAR(50),
    DungLuong VARCHAR(50),
    ChuanKetNoi VARCHAR(50),
    KichCo VARCHAR(50),
    TocDoDocGhi VARCHAR(100),
    CONSTRAINT FK_CHI_TIET_O_CUNG_SAN_PHAM
        FOREIGN KEY (MaSP) REFERENCES SAN_PHAM(MaSP)
        ON DELETE CASCADE
        ON UPDATE CASCADE
) ENGINE=InnoDB;

CREATE TABLE CHI_TIET_RAM (
    MaSP INT PRIMARY KEY,
    LoaiRam VARCHAR(50),
    DungLuong VARCHAR(50),
    BusRam VARCHAR(50),
    DienAp VARCHAR(50),
    SoThanh INT,
    CONSTRAINT FK_CHI_TIET_RAM_SAN_PHAM
        FOREIGN KEY (MaSP) REFERENCES SAN_PHAM(MaSP)
        ON DELETE CASCADE
        ON UPDATE CASCADE
) ENGINE=InnoDB;

-- =========================
-- 5. GIỎ HÀNG
-- =========================
CREATE TABLE GIO_HANG (
    MaGioHang INT AUTO_INCREMENT PRIMARY KEY,
    MaKH INT NOT NULL UNIQUE,
    NgayCapNhat DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT FK_GIO_HANG_KHACH_HANG
        FOREIGN KEY (MaKH) REFERENCES KHACH_HANG(MaKH)
        ON DELETE CASCADE
        ON UPDATE CASCADE
) ENGINE=InnoDB;

CREATE TABLE CHI_TIET_GIO_HANG (
    MaGioHang INT NOT NULL,
    MaSP INT NOT NULL,
    SoLuong INT NOT NULL DEFAULT 1,
    DonGia DECIMAL(15,2) NOT NULL DEFAULT 0,
    PRIMARY KEY (MaGioHang, MaSP),
    CONSTRAINT FK_CTGH_GIO_HANG
        FOREIGN KEY (MaGioHang) REFERENCES GIO_HANG(MaGioHang)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    CONSTRAINT FK_CTGH_SAN_PHAM
        FOREIGN KEY (MaSP) REFERENCES SAN_PHAM(MaSP)
        ON DELETE CASCADE
        ON UPDATE CASCADE
) ENGINE=InnoDB;

CREATE INDEX IDX_CTGH_MaSP ON CHI_TIET_GIO_HANG(MaSP);

-- =========================
-- 6. ĐƠN HÀNG
-- =========================
CREATE TABLE DON_HANG (
    MaDonHang INT AUTO_INCREMENT PRIMARY KEY,
    MaKH INT NOT NULL,
    MaNV INT NULL,
    NgayDat DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DiaChiNhan VARCHAR(255) NOT NULL,
    SDTNhan VARCHAR(15) NOT NULL,
    TongTien DECIMAL(15,2) NOT NULL DEFAULT 0,
    PhiVanChuyen DECIMAL(15,2) NOT NULL DEFAULT 0,
    TrangThaiDonHang ENUM('CHO_XAC_NHAN', 'DA_XAC_NHAN', 'DANG_GIAO', 'DA_GIAO', 'DA_HUY') NOT NULL DEFAULT 'CHO_XAC_NHAN',
    GhiChu TEXT,
    MaKM INT NULL,
    CONSTRAINT FK_DON_HANG_KHACH_HANG
        FOREIGN KEY (MaKH) REFERENCES KHACH_HANG(MaKH)
        ON DELETE RESTRICT
        ON UPDATE CASCADE,
    CONSTRAINT FK_DON_HANG_QUAN_TRI_VIEN
        FOREIGN KEY (MaNV) REFERENCES QUAN_TRI_VIEN(MaNV)
        ON DELETE SET NULL
        ON UPDATE CASCADE,
    CONSTRAINT FK_DON_HANG_KHUYEN_MAI
        FOREIGN KEY (MaKM) REFERENCES KHUYEN_MAI(MaKM)
        ON DELETE SET NULL
        ON UPDATE CASCADE
) ENGINE=InnoDB;

CREATE INDEX IDX_DON_HANG_MaKH ON DON_HANG(MaKH);
CREATE INDEX IDX_DON_HANG_MaNV ON DON_HANG(MaNV);

CREATE TABLE CHI_TIET_DON_HANG (
    MaDonHang INT NOT NULL,
    MaSP INT NOT NULL,
    SoLuong INT NOT NULL,
    DonGia DECIMAL(15,2) NOT NULL,
    ThanhTien DECIMAL(15,2) NOT NULL,
    PRIMARY KEY (MaDonHang, MaSP),
    CONSTRAINT FK_CTDH_DON_HANG
        FOREIGN KEY (MaDonHang) REFERENCES DON_HANG(MaDonHang)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    CONSTRAINT FK_CTDH_SAN_PHAM
        FOREIGN KEY (MaSP) REFERENCES SAN_PHAM(MaSP)
        ON DELETE RESTRICT
        ON UPDATE CASCADE
) ENGINE=InnoDB;

CREATE INDEX IDX_CTDH_MaSP ON CHI_TIET_DON_HANG(MaSP);

-- =========================
-- 7. THANH TOÁN
-- =========================
CREATE TABLE PHUONG_THUC_THANH_TOAN (
    MaPTTT INT AUTO_INCREMENT PRIMARY KEY,
    TenPTTT VARCHAR(100) NOT NULL UNIQUE,
    MoTa TEXT,
    TrangThai TINYINT NOT NULL DEFAULT 1
) ENGINE=InnoDB;

CREATE TABLE THANH_TOAN (
    MaThanhToan INT AUTO_INCREMENT PRIMARY KEY,
    MaDonHang INT NOT NULL UNIQUE,
    MaPTTT INT NOT NULL,
    SoTien DECIMAL(15,2) NOT NULL,
    ThoiGianThanhToan DATETIME DEFAULT CURRENT_TIMESTAMP,
    TrangThaiThanhToan ENUM('CHUA_THANH_TOAN', 'DA_THANH_TOAN', 'HOAN_TIEN') NOT NULL DEFAULT 'CHUA_THANH_TOAN',
    MaGiaoDich VARCHAR(100),
    TenNganHang VARCHAR(100),
    CONSTRAINT FK_THANH_TOAN_DON_HANG
        FOREIGN KEY (MaDonHang) REFERENCES DON_HANG(MaDonHang)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    CONSTRAINT FK_THANH_TOAN_PTTT
        FOREIGN KEY (MaPTTT) REFERENCES PHUONG_THUC_THANH_TOAN(MaPTTT)
        ON DELETE RESTRICT
        ON UPDATE CASCADE
) ENGINE=InnoDB;

CREATE INDEX IDX_THANH_TOAN_MaPTTT ON THANH_TOAN(MaPTTT);

-- =========================
-- 8. KHUYẾN MÃI
-- =========================
CREATE TABLE KHUYEN_MAI (
    MaKM INT AUTO_INCREMENT PRIMARY KEY,
    TenKM VARCHAR(150) NOT NULL,
    LoaiGiam ENUM('PHAN_TRAM', 'SO_TIEN') NOT NULL,
    GiaTriGiam DECIMAL(15,2) NOT NULL DEFAULT 0,
    NgayBatDau DATETIME NOT NULL,
    NgayKetThuc DATETIME NOT NULL,
    TrangThai TINYINT NOT NULL DEFAULT 1,
    MaNV INT NULL,
    CONSTRAINT FK_KHUYEN_MAI_QUAN_TRI_VIEN
        FOREIGN KEY (MaNV) REFERENCES QUAN_TRI_VIEN(MaNV)
        ON DELETE SET NULL
        ON UPDATE CASCADE
) ENGINE=InnoDB;

CREATE INDEX IDX_KHUYEN_MAI_MaNV ON KHUYEN_MAI(MaNV);

CREATE TABLE KHUYEN_MAI_SAN_PHAM (
    MaKM INT NOT NULL,
    MaSP INT NOT NULL,
    PRIMARY KEY (MaKM, MaSP),
    CONSTRAINT FK_KMSP_KHUYEN_MAI
        FOREIGN KEY (MaKM) REFERENCES KHUYEN_MAI(MaKM)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    CONSTRAINT FK_KMSP_SAN_PHAM
        FOREIGN KEY (MaSP) REFERENCES SAN_PHAM(MaSP)
        ON DELETE CASCADE
        ON UPDATE CASCADE
) ENGINE=InnoDB;

CREATE INDEX IDX_KMSP_MaSP ON KHUYEN_MAI_SAN_PHAM(MaSP);

-- =========================
-- 9. ĐÁNH GIÁ
-- =========================
CREATE TABLE DANH_GIA (
    MaDG INT AUTO_INCREMENT PRIMARY KEY,
    MaKH INT NOT NULL,
    MaSP INT NOT NULL,
    SoSao TINYINT NOT NULL,
    NoiDung TEXT,
    NgayDanhGia DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    TrangThaiDuyet TINYINT NOT NULL DEFAULT 0,
    CONSTRAINT FK_DANH_GIA_KHACH_HANG
        FOREIGN KEY (MaKH) REFERENCES KHACH_HANG(MaKH)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    CONSTRAINT FK_DANH_GIA_SAN_PHAM
        FOREIGN KEY (MaSP) REFERENCES SAN_PHAM(MaSP)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    CONSTRAINT UQ_DANH_GIA UNIQUE (MaKH, MaSP)
) ENGINE=InnoDB;

CREATE INDEX IDX_DANH_GIA_MaSP ON DANH_GIA(MaSP);

-- =========================
-- 10. DỮ LIỆU MẪU CƠ BẢN
-- =========================
INSERT INTO LOAI_SAN_PHAM (TenLoaiSP, MoTa) VALUES
('Mainboard', 'Bo mạch chủ'),
('CPU', 'Bộ vi xử lý'),
('VGA', 'Card đồ họa'),
('Case', 'Vỏ máy tính'),
('Nguồn', 'Bộ nguồn máy tính'),
('Tản nhiệt', 'Thiết bị tản nhiệt'),
('Ổ cứng', 'HDD/SSD'),
('RAM', 'Bộ nhớ trong');

INSERT INTO PHUONG_THUC_THANH_TOAN (TenPTTT, MoTa, TrangThai) VALUES
('COD', 'Thanh toán khi nhận hàng', 1),
('Chuyển khoản', 'Thanh toán qua ngân hàng', 1),
('Ví điện tử', 'Thanh toán qua ví điện tử', 1);

SET FOREIGN_KEY_CHECKS = 1;
